### ISSUE TITLE
Users are removed from groups after subsequent logins

### ISSUE THREAD

**Issue by kensykora** [SonarQubeCommunity/sonar-auth-aad#36]
SonarQube Version:7.0.0.36138
sonar-auth-aad Version: 1.1-RC1

I'm running into the following issue:

 1. I log in with a new user from Azure AD. They have an account created correctly in SonarQube.
 2. On another admin account, I add the user into the built-in group sonar-administrators
 3. I observe the user is added correctly.

However, The next time the user I added to the admin group logs in, they are immediately removed from the admin group. and don't have admin privileges.

Any idea how I can address this issue?

**Comment by julienlancelot** [comment]
This is because you have activated "Enable Groups Synchronization" setting. This setting means that each time a user authenticate on SonarQube using AAD, the user will be associated only to his Azure AD group. 
If the user has been associated to group into SonarQube, but he's not associated to this group on Azure, the association will be removed.

**Comment by kensykora** [comment]
Thanks!
