### ISSUE TITLE
Getting a 404 when trying to sign in

### ISSUE THREAD

**Issue by cwoolumtechnossus** [SonarQubeCommunity/sonar-auth-aad#4]
When I click the 'Log in with Azure AD' button, i get the following message:

![image](https://cloud.githubusercontent.com/assets/16725244/16323974/4354fab0-3964-11e6-8cc1-1ef656dca62b.png)

This is the URL it is trying to hit. Is something configured wrong?

https://sq.mydomain.com/common/oauth2/authorize?client_id=c011219f-1530-4992-9814-1c8d261f45de&response_type=code&redirect_uri=https://sq.mydomain.com/oauth2/callback/aad&state=vmgfu2e4523432qcqnfoabl0in

**Comment by hkamel** [comment]
Hello @cwoolumtechnossus, are you exposing SonarQube behind a reversed proxy? the URL above is incorrect (most probably due to incorrect URL rewriting) the URL should be https://login.microsoftonline.com/common/oauth2/authorize?client_id=c011219f-1530-4992-9814-1c8d261f45de&response_type=code&redirect_uri=https://sq.mydomain.com/oauth2/callback/aad&state=vmgfu2e4523432qcqnfoabl0in 

If you're using IIS as a reversed proxy, please follow this instructions https://blogs.msdn.microsoft.com/visualstudioalmrangers/2016/06/04/running-sonarqube-behind-an-iis-reversed-proxy/

**Comment by cwoolumtechnossus** [comment]
I am using the reverse proxy.I had previously configure my Reverse Proxt using the Jesse Houwing blog article. The blog above added an ORIGINAL_URL server variable but it didn't seem to make any difference. Isn't SonarQube generating the Url?

**Comment by hkamel** [comment]
Please make sure you disable "Reverse rewrite host in response headers" in the ARR settings 
![image](https://cloud.githubusercontent.com/assets/5002831/16391512/94e753ee-3cb8-11e6-8827-f6a932087276.png)

**Comment by cwoolumtechnossus** [comment]
That was the missing piece! Thanks!
