### ISSUE TITLE
Adding properties directory in sonar.properties

### ISSUE THREAD

**Issue by gauravojha** [SonarQubeCommunity/sonar-auth-aad#42]
Hi,

I was trying to automate the installation through a Chef cookbook. So, I added the plugin properties (such as sonar.auth.aad.enable) directly in sonar.properties and dont want to open the browser to enable them. Now when Sonar comes up, the UI behaves weirdly. It enables Azure AD and everything, but the switch which signifies is still pointing to False. Please note that the value to Reset it has been enabled. 

Would really appreciate if someone could help or guide in fixing this anomaly. 

Have sent an email to the SonarQube Google group as well. But would really appreciate any help here as well. Attaching the screenshots for reference.

![login](https://user-images.githubusercontent.com/10114860/40562918-ea76fb3c-6030-11e8-9f32-0b8d6c594caf.PNG)
![settings](https://user-images.githubusercontent.com/10114860/40562919-ea86b4d2-6030-11e8-9f3f-10eb9c981a9a.png)
![sonarproperties](https://user-images.githubusercontent.com/10114860/40562920-ea937a28-6030-11e8-9767-3b8d604a35e6.png)

**Comment by julienlancelot** [comment]
As you've defined such settings in sonar.properties, they are indeed well taken into account in the server, but they are not visible in the UI nor the WS.
The ability to use sonar.properties file is there in order to more easily create some scripts to install a SonarQube server, but for the moment nothing is reflected in UI/WS.
We'll see how we could improve this.

If you want to see the settings in the UI, you need to remove their definitions in sonar.properties, and you need to use the api/settings/set WS after SonarQube startup.

**Comment by gauravojha** [comment]
Thank you. I just did that and used the APIs.
